drink_recipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls", namespace="users")),
    path("api/v1/", include("myApp.api_urls", namespace="api")),
    path("", include("myApp.urls", namespace="myApp")),
]

# check if debug is true(for local works not production) then handle the media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myApp/urls.py
from django.urls import path
from . import views

app_name = "myApp"

urlpatterns = [
    path("add_to_favorite/<int:pk>", views.add_to_favorite, name="add_favorite"),
    path("delete_favorite/<int:pk>/", views.delete_favorite, name="delete_favorite"),
    path("rating_form/<int:pk>/", views.RatingFormView.as_view(), name="rating_form"),
    path(
        "favorite_detail/<int:pk>/",
        views.MyFavoriteDetailView.as_view(),
        name="detail_favorite",
    ),
    path("search", views.SearchView.as_view(), name="search"),
    path("my_favorites/", views.my_favorites, name="my_favorites"),
    path("", views.IndexView.as_view(), name="index"),
]

users/urls.py
from . import views
from django.urls import path, include


app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", views.UserCreateView.as_view(), name="signup"),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Drinker!</title>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'myApp/css/base.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% bootstrap_css %}
</head>
<body>
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <!-- Navigation Links -->
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'myApp:index' %}" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="{% url 'myApp:search' %}" class="nav-link px-2 text-white">Search</a></li>
                
                {% if user.is_authenticated %}
                <li><a href="{% url 'myApp:my_favorites' %}" class="nav-link px-2 text-white">My Favorites</a></li>
                <li>
                    <form action="{% url 'users:logout' %}" method="post">
                        <button type="submit" class="nav-link px-2 text-white">Logout</button>
                        {% csrf_token %}
                    </form>
                </li>
                {% else %}
                <li><a href="{% url 'users:login' %}" class="nav-link px-2 text-white">Login</a></li>
                <li><a href="{% url 'users:signup' %}" class="nav-link px-2 text-white">Signup</a></li>

                {% endif %}
                    
            </ul>
            <!-- Search Form -->
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 d-flex" role="search" method="get" action="{% url 'myApp:search' %}">
                <input type="text" name="query" class="form-control mx-1" placeholder="Search a drink..." aria-label="Search">
                <button type="submit" class="btn btn-outline-primary btn-sm">Search</button>
            </form>
        </div>
    </div>
</header>
{% bootstrap_messages %}
<div class="container my-3">{% block content %} {% endblock content %}</div>

<footer class="container py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© {% now 'Y' %} By Aman~TheNucleya, Powered by <a href="https://www.thecocktaildb.com/api.php">TheCocktailDB</a></p>
</footer>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous">
</script>
{% bootstrap_javascript %}
</body>
</html>